import {
    faBolt,
    faBook,
    faDragon,
    faFilm,
    faFistRaised,
    faFootballBall,
    faGhost,
    faHatCowboy,
    faHatCowboySide,
    faHeart,
    faHelmetSafety,
    faHome,
    faLandmark,
    faLaugh,
    faMagnifyingGlass,
    faMap,
    faMask,
    faMicrophone,
    faMusic,
    faRocket,
    faTheaterMasks,
    faUser,
} from '@fortawesome/free-solid-svg-icons'
import { Genre } from '../genres.interface'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'

export const MovieGenres: Genre[] = [
    {
        value: 'action',
        label: 'Action',
        href: '/search?sort=trending&genre=action',
        icon: <FontAwesomeIcon icon={faFistRaised} />,
        description: 'Movies with a lot of exciting action and adventure.',
    },
    {
        value: 'adventure',
        label: 'Adventure',
        href: '/search?sort=trending&genre=adventure',
        icon: <FontAwesomeIcon icon={faMap} />,
        description: 'Movies filled with epic journeys and exploration.',
    },
    {
        value: 'animation',
        label: 'Animation',
        href: '/search?sort=trending&genre=animation',
        icon: <FontAwesomeIcon icon={faFilm} />,
        description: 'Movies with animated characters and stories.',
    },
    {
        value: 'biography',
        label: 'Biography',
        href: '/search?sort=trending&genre=biography',
        icon: <FontAwesomeIcon icon={faUser} />,
        description: 'Movies based on the lives of real people.',
    },
    {
        value: 'comedy',
        label: 'Comedy',
        href: '/search?sort=trending&genre=comedy',
        icon: <FontAwesomeIcon icon={faLaugh} />,
        description: 'Movies designed to make you laugh.',
    },
    {
        value: 'crime',
        label: 'Crime',
        href: '/search?sort=trending&genre=crime',
        icon: <FontAwesomeIcon icon={faMask} />,
        description: 'Movies focused on crime and criminal activities.',
    },
    {
        value: 'documentary',
        label: 'Documentary',
        href: '/search?sort=trending&genre=documentary',
        icon: <FontAwesomeIcon icon={faBook} />,
        description: 'Movies that document real-life events.',
    },
    {
        value: 'drama',
        label: 'Drama',
        href: '/search?sort=trending&genre=drama',
        icon: <FontAwesomeIcon icon={faTheaterMasks} />,
        description: 'Movies with intense character development and stories.',
    },
    {
        value: 'family',
        label: 'Family',
        href: '/search?sort=trending&genre=family',
        icon: <FontAwesomeIcon icon={faHome} />,
        description: 'Movies suitable for a family audience.',
    },
    {
        value: 'fantasy',
        label: 'Fantasy',
        href: '/search?sort=trending&genre=fantasy',
        icon: <FontAwesomeIcon icon={faDragon} />,
        description: 'Movies with magical and otherworldly elements.',
    },
    {
        value: 'film-noir',
        label: 'Film-Noir',
        href: '/search?sort=trending&genre=film-noir',
        icon: <FontAwesomeIcon icon={faHatCowboy} />,
        description:
            'Stylized movies with a cynical attitude and moral ambiguity.',
    },
    {
        value: 'history',
        label: 'History',
        href: '/search?sort=trending&genre=history',
        icon: <FontAwesomeIcon icon={faLandmark} />,
        description: 'Movies that portray historical events.',
    },
    {
        value: 'horror',
        label: 'Horror',
        href: '/search?sort=trending&genre=horror',
        icon: <FontAwesomeIcon icon={faGhost} />,
        description: 'Movies designed to scare and shock.',
    },
    {
        value: 'music',
        label: 'Music',
        href: '/search?sort=trending&genre=music',
        icon: <FontAwesomeIcon icon={faMusic} />,
        description: 'Movies centered around music and musicians.',
    },
    {
        value: 'musical',
        label: 'Musical',
        href: '/search?sort=trending&genre=musical',
        icon: <FontAwesomeIcon icon={faMicrophone} />,
        description:
            'Movies where characters express themselves through song and dance.',
    },
    {
        value: 'mystery',
        label: 'Mystery',
        href: '/search?sort=trending&genre=mystery',
        icon: <FontAwesomeIcon icon={faMagnifyingGlass} />,
        description: 'Movies involving suspense and unsolved cases.',
    },
    {
        value: 'romance',
        label: 'Romance',
        href: '/search?sort=trending&genre=romance',
        icon: <FontAwesomeIcon icon={faHeart} />,
        description: 'Movies focused on love and relationships.',
    },
    {
        value: 'sci-fi',
        label: 'Sci-Fi',
        href: '/search?sort=trending&genre=sci-fi',
        icon: <FontAwesomeIcon icon={faRocket} />,
        description: 'Movies with futuristic and technological themes.',
    },
    {
        value: 'sport',
        label: 'Sport',
        href: '/search?sort=trending&genre=sport',
        icon: <FontAwesomeIcon icon={faFootballBall} />,
        description: 'Movies centered around sports and athletes.',
    },
    {
        value: 'thriller',
        label: 'Thriller',
        href: '/search?sort=trending&genre=thriller',
        icon: <FontAwesomeIcon icon={faBolt} />,
        description: 'Movies designed to keep you on the edge of your seat.',
    },
    {
        value: 'war',
        label: 'War',
        href: '/genres/war',
        icon: <FontAwesomeIcon icon={faHelmetSafety} />,
        description: 'Movies that depict war and military conflicts.',
    },
    {
        value: 'western',
        label: 'Western',
        href: '/genres/western',
        icon: <FontAwesomeIcon icon={faHatCowboySide} />,
        description: 'Movies set in the American Old West.',
    },
]
