import {
    faBolt,
    faBook,
    faDragon,
    faFilm,
    faFistRaised,
    faFootballBall,
    faGhost,
    faHatCowboy,
    faHatCowboySide,
    faHeart,
    faHelmetSafety,
    faHome,
    faLandmark,
    faLaugh,
    faMagnifyingGlass,
    faMap,
    faMask,
    faMicrophone,
    faMusic,
    faRocket,
    faTheaterMasks,
    faUser,
} from '@fortawesome/free-solid-svg-icons'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
export enum ShowGenreTitles {
    'action',
    'adventure',
    'all',
    'animation',
    'biography',
    'comedy',
    'drama',
    'fantasy',
    'horror',
    'mystery',
    'Sci-Fi',
    'Thriller',
}
export const ShowGenres: {
    value: keyof typeof ShowGenreTitles
    label: string
    href: string
    icon: JSX.Element
    description: string
}[] = [
    {
        value: 'action',
        label: 'Action',
        href: '/shows?sort=trending&genre=action',
        icon: <FontAwesomeIcon icon={faFistRaised} />,
        description: 'Movies with a lot of exciting action and adventure.',
    },
    {
        value: 'adventure',
        label: 'Adventure',
        href: '/shows?sort=trending&genre=adventure',
        icon: <FontAwesomeIcon icon={faMap} />,
        description: 'Movies filled with epic journeys and exploration.',
    },
    {
        value: 'animation',
        label: 'Animation',
        href: '/shows?sort=trending&genre=animation',
        icon: <FontAwesomeIcon icon={faFilm} />,
        description: 'Movies with animated characters and stories.',
    },
    // {
    //     value: 'biography',
    //     label: 'Biography',
    //     href: '/shows?sort=trending&genre=biography',
    //     icon: <FontAwesomeIcon icon={faUser} />,
    //     description: 'Movies based on the lives of real people.',
    // },
    {
        value: 'comedy',
        label: 'Comedy',
        href: '/shows?sort=trending&genre=comedy',
        icon: <FontAwesomeIcon icon={faLaugh} />,
        description: 'Movies designed to make you laugh.',
    },
    // {
    //     value: 'crime',
    //     label: 'Crime',
    //     href: '/shows?sort=trending&genre=crime',
    //     icon: <FontAwesomeIcon icon={faMask} />,
    //     description: 'Movies focused on crime and criminal activities.',
    // },
    // {
    //     value: 'documentary',
    //     label: 'Documentary',
    //     href: '/shows?sort=trending&genre=documentary',
    //     icon: <FontAwesomeIcon icon={faBook} />,
    //     description: 'Movies that document real-life events.',
    // },
    {
        value: 'drama',
        label: 'Drama',
        href: '/shows?sort=trending&genre=drama',
        icon: <FontAwesomeIcon icon={faTheaterMasks} />,
        description: 'Movies with intense character development and stories.',
    },
    // {
    //     value: 'family',
    //     label: 'Family',
    //     href: '/shows?sort=trending&genre=family',
    //     icon: <FontAwesomeIcon icon={faHome} />,
    //     description: 'Movies suitable for a family audience.',
    // },
    // {
    //     value: 'fantasy',
    //     label: 'Fantasy',
    //     href: '/shows?sort=trending&genre=fantasy',
    //     icon: <FontAwesomeIcon icon={faDragon} />,
    //     description: 'Movies with magical and otherworldly elements.',
    // },
    // {
    //     value: 'film-noir',
    //     label: 'Film-Noir',
    //     href: '/shows?sort=trending&genre=film-noir',
    //     icon: <FontAwesomeIcon icon={faHatCowboy} />,
    //     description:
    //         'Stylized movies with a cynical attitude and moral ambiguity.',
    // },
    // {
    //     value: 'history',
    //     label: 'History',
    //     href: '/shows?sort=trending&genre=history',
    //     icon: <FontAwesomeIcon icon={faLandmark} />,
    //     description: 'Movies that portray historical events.',
    // },
    {
        value: 'horror',
        label: 'Horror',
        href: '/shows?sort=trending&genre=horror',
        icon: <FontAwesomeIcon icon={faGhost} />,
        description: 'Movies designed to scare and shock.',
    },
    // {
    //     value: 'music',
    //     label: 'Music',
    //     href: '/shows?sort=trending&genre=music',
    //     icon: <FontAwesomeIcon icon={faMusic} />,
    //     description: 'Movies centered around music and musicians.',
    // },
    // {
    //     value: 'musical',
    //     label: 'Musical',
    //     href: '/shows?sort=trending&genre=musical',
    //     icon: <FontAwesomeIcon icon={faMicrophone} />,
    //     description:
    //         'Movies where characters express themselves through song and dance.',
    // },
    {
        value: 'mystery',
        label: 'Mystery',
        href: '/shows?sort=trending&genre=mystery',
        icon: <FontAwesomeIcon icon={faMagnifyingGlass} />,
        description: 'Movies involving suspense and unsolved cases.',
    },
    // {
    //     value: 'romance',
    //     label: 'Romance',
    //     href: '/shows?sort=trending&genre=romance',
    //     icon: <FontAwesomeIcon icon={faHeart} />,
    //     description: 'Movies focused on love and relationships.',
    // },
    // {
    //     value: 'sci-fi',
    //     label: 'Sci-Fi',
    //     href: '/shows?sort=trending&genre=sci-fi',
    //     icon: <FontAwesomeIcon icon={faRocket} />,
    //     description: 'Movies with futuristic and technological themes.',
    // },
    // {
    //     value: 'sport',
    //     label: 'Sport',
    //     href: '/shows?sort=trending&genre=sport',
    //     icon: <FontAwesomeIcon icon={faFootballBall} />,
    //     description: 'Movies centered around sports and athletes.',
    // },
    // {
    //     value: 'thriller',
    //     label: 'Thriller',
    //     href: '/shows?sort=trending&genre=thriller',
    //     icon: <FontAwesomeIcon icon={faBolt} />,
    //     description: 'Movies designed to keep you on the edge of your seat.',
    // },
    // {
    //     value: 'war',
    //     label: 'War',
    //     href: '/genres/war',
    //     icon: <FontAwesomeIcon icon={faHelmetSafety} />,
    //     description: 'Movies that depict war and military conflicts.',
    // },
    // {
    //     value: 'western',
    //     label: 'Western',
    //     href: '/genres/western',
    //     icon: <FontAwesomeIcon icon={faHatCowboySide} />,
    //     description: 'Movies set in the American Old West.',
    // },
]
